version: '3.8'

volumes:
  wordpress:
  db:

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${DB_USER_NAME}
      - WORDPRESS_DB_PASSWORD=${DB_USER_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
    restart: always

  db:
    image: mysql:5.7
    container_name: db
    environment: 
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER_NAME}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes: 
      - db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --sql_mode=""
    restart: always